// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MyRMSELoss
Rcpp::NumericVector MyRMSELoss(const Rcpp::NumericVector& ys, const Rcpp::NumericVector& yhats);
RcppExport SEXP oddvibe_MyRMSELoss(SEXP ysSEXP, SEXP yhatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type yhats(yhatsSEXP);
    rcpp_result_gen = Rcpp::wrap(MyRMSELoss(ys, yhats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"oddvibe_MyRMSELoss", (DL_FUNC) &oddvibe_MyRMSELoss, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_oddvibe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
