// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FindOutlierWeights
NumericVector FindOutlierWeights(const NumericMatrix& xs, const NumericVector& ys, const size_t nrounds, const size_t seed);
RcppExport SEXP oddvibe_FindOutlierWeights(SEXP xsSEXP, SEXP ysSEXP, SEXP nroundsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ys(ysSEXP);
    Rcpp::traits::input_parameter< const size_t >::type nrounds(nroundsSEXP);
    Rcpp::traits::input_parameter< const size_t >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(FindOutlierWeights(xs, ys, nrounds, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"oddvibe_FindOutlierWeights", (DL_FUNC) &oddvibe_FindOutlierWeights, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_oddvibe(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
